name: Deploy Blog Application

on:
  push:
    branches:
    - main
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t shubnit12/personalblogwebsite .
      - name: Publish Image to DockerHub
        run: docker push shubnit12/personalblogwebsite:latest
 run_docker_container_on_ec2:
  needs: build
  runs-on: self-hosted
  steps:
      - name: Pull Image From Docker Hub
        run: docker pull shubnit12/personalblogwebsite:latest
      - name: Remove old container
        run: |
          docker rm -f blog-app-container || true
      - name: Remove old container
        run: |
          docker system prune -a -f || true
      - name: Run Docker Container
        run: |
          docker run -d \
            -p 3000:3000 \
            --name blog-app-container \
            shubnit12/personalblogwebsite:latest
